### ISSUE TITLE
Seria possível quantificar os acertos? Tipo X%

### ISSUE THREAD

**Issue by alinebenevides** [leolca/tex-hyphen-pt#16]
https://github.com/leolca/tex-hyphen-pt/blob/62227b4a7f911e863ea704968e1603a06253b8db/article/article.tex#L443C64-L444C55

Leo,
se tivermos um número de acertos, creio que justificaria melhor a proposta de revisar as regras.

**Comment by leolca** [comment]
Sim. Mas é necessário primeiro definir o dicionário de hifenizações padrão ouro 🏆.
