### ISSUE TITLE
Justificativa para alguns erros que não conseguiremos resolver.

### ISSUE THREAD

**Issue by alinebenevides** [leolca/tex-hyphen-pt#2]
https://github.com/leolca/tex-hyphen-pt/blob/7d38f23769aad21c42e2c438668d28c8a3877d77/article/article.tex#L694

Although the 132 words have some common characteristics, which would allow, to some extent, to reduce the amount of hyphenation errors, there is a limitation arising from the way TeX rules are conceived. We present, below, the systematicities found in these data that could be predicted by another structure of rules:

**Morphological determination:**
Prefixes such as _re-, sub-, cyber-_ and _auto-_ require separating the prefix from its stem, which runs into phonological issues. For example, _reiniciar_ and s_ublinhar_, as they contain prefixes, must be hyphenated as _re-i-ni-ci-ar_ and _sub-li-nhar_, respecting the morphological formation of the word. However, considering that the Portuguese language hyphenates its words from syllabic phonological correlates, words that require morphological information such as these do not have their hyphenation performed properly. They total, in the corpus in question, eight words with _re-_, one case with _auto-, meta-, sub-, cyber-, geo-_ and _neuro-_.

**Foreignness:**
There is a group of 20 words in the corpus that are terminologies or words that were incorporated into the Portuguese language without full phonological adaptation, such as _darwinismo, quilowatt_ and _esfiha_. The lack of adaptation makes the phonological pattern very specific to the word, making it impossible or costly for TeX to incorporate a specific rule.

_Word-initial consonant clusters_
Portuguese has few cases of consonant clusters at the beginning of a word. They, in general, are etymological remnants and are currently unproductive in the language, since there are no neologisms with this pattern. Encounters like _ps-_ and _pn-_ are more frequent, as they are present in words like _psicologia_ and _pneu_, which have an average frequency in the language, which can be predicted by rules, which comprise X words. However, there are consonant clusters that are found in very specific words and of very rare frequency, so that marking them, although possible, is costly for the program, as it requires marking very specific consonant clusters, as in _dzeta, gnu, cnidário, ftálico_ and _gnaisse_  - that is, just five words.

**Comment by leolca** [comment]
I believe you tagged the wrong line. There is nothing about "the 132 words" in the context of [line 694](https://github.com/leolca/tex-hyphen-pt/blob/7d38f23769aad21c42e2c438668d28c8a3877d77/article/article.tex#L694).
