### ISSUE TITLE
Não só em início de sílaba, mas de palavra tbm, não? Se for no meio da palavra, elas se separam.

### ISSUE THREAD

**Issue by alinebenevides** [leolca/tex-hyphen-pt#20]
https://github.com/leolca/tex-hyphen-pt/blob/62227b4a7f911e863ea704968e1603a06253b8db/article/article.tex#L623C34-L623C72

**Comment by leolca** [comment]
Início de palavra é obrigatoriamente um início de sílaba. Talvez a questão aqui seriam os clusters consonantais que são possíveis em início de palavra. Exemplos: **pn**, **ps** e **mn** (como em: _**pn**eumático_, _**ps**icólogo_ e _**mn**emônico_). Tais clusters consonantais não se separam, quer em início ou meio de palavras. Temos: _**pn**eu-má-ti-co_, _**ps**i-có-lo-go_ e _**mn**e-mô-ni-co_, em início de palavra, e temos _ele-tro-**pn**eu-má-ti-co_, _hi-dro-**pn**eu-má-ti-co_, _neu-ro-**ps**i-có-lo-go_ e _me-ta-**mn**e-mô-ni-co_ no meio de palavras.
