### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by alinebenevides** [leolca/tex-hyphen-pt#25]
https://github.com/leolca/tex-hyphen-pt/blob/62227b4a7f911e863ea704968e1603a06253b8db/article/article.tex#L890

Leo,
por que as regras gerais não conseguem separar adequadamente este padrão? Qual é o erro geral que era produzido? Pergunto porque é claramente uma palavra CV-CV-CV, o que, ao meu ver, não daria problema. Percebi que tem relação com ô, qual é a inconsistência?

**Comment by leolca** [comment]
Só tínhamos a regra `1lo`, `1ló` e `1lõ`, mas não a regra  `1lô`, sendo assim necessário acrescentá-la.
