### ISSUE TITLE
qual é o tamanho do artigo em termos de páginas? 

### ISSUE THREAD

**Issue by alinebenevides** [leolca/tex-hyphen-pt#3]
https://github.com/leolca/tex-hyphen-pt/blob/7d38f23769aad21c42e2c438668d28c8a3877d77/article/article.tex#L54

Qual é o tamanho do artigo? Para saber o que tirar ou inserir.

**Comment by leolca** [comment]
Como conversamos, vamos fazer uma versão completa (inicialmente sem limite de páginas), funcionando como um relatório. Depois faremos uma versão bem resumida para a TUGboat e uma versão completa para uma revista a decidir.
