### ISSUE TITLE
Rever os exemplos

### ISSUE THREAD

**Issue by alinebenevides** [leolca/tex-hyphen-pt#36]
https://github.com/leolca/tex-hyphen-pt/blob/08583161a086c26b21025f58897fc3d876e27ba6/article/article.tex#L837

Leo,
eu não entendi os exemplos con-nos-co e co-mum-men-te, pois não temos esses dígrafos ortograficamente no português.

**Comment by leolca** [comment]
Trata-se da grafia no Português Europeu. Algumas diferenças permanecem mesmo após o Acordo Ortográfico.  https://www.flip.pt/Duvidas-Linguisticas/Duvida-Linguistica/DID/3972
