### ISSUE TITLE
exemplificar

### ISSUE THREAD

**Issue by alinebenevides** [leolca/tex-hyphen-pt#39]
https://github.com/leolca/tex-hyphen-pt/blob/08583161a086c26b21025f58897fc3d876e27ba6/article/article.tex#L955

Leo,
creio que seria legal exemplificar aqui, pois em casos como história, em que há diacrítico, ela é, de fato, paroxítona, mas não me ocorreu um caso sem diacrítico que seja proparoxítona, pois todas as proparoxítonas são acentuadas. Quais seriam os exemplos do segundo caso?

**Comment by leolca** [comment]
_história_ é um exemplo... a maioria dos dicionários utiliza a hifenização _his-tó-ria_, mas há um dicionários marcando como _his-tó-ri:a_ (ou seja, aceitando as versões _his-tó-ria_ e _his-tó-ri-a_).
O problema aqui a ser corrigido são casos como: _po-lí-ci-a_, _mi-nis-té-ri-o_, _a-gên-ci-a_, _pró-pri-o_, etc., selecionando a forma sem a última separação silábica: _po-lí-cia_, _mi-nis-té-rio_, _a-gên-cia_, _pró-prio_, etc.
