### ISSUE TITLE
Letra H

### ISSUE THREAD

**Issue by alinebenevides** [leolca/tex-hyphen-pt#43]
https://github.com/leolca/tex-hyphen-pt/blob/dd17f359ec18c5fab0838453389bd8b4f40ca2b7/article/texrulespt.tex#L22

Léo,
há uma justificativa para não considerarem o H (hábito, hiato, holocausto etc.)? Valeria inserir a justificativa em uma nota de rodapé, não?

**Comment by leolca** [comment]
Em geral, o H aparece em início de palavra, antes de L, N ou C. Os exemplos que encontrei que fogem deste padrão foram: Bahia, Corinthians, show, shopping, Matheus,... ou seja, nomes próprios ou empréstimos linguísticos não adaptados.  Quando no início de palavra, não existe necessidade de marcar como ponto de hifenização.
