### ISSUE TITLE
sobre W

### ISSUE THREAD

**Issue by alinebenevides** [leolca/tex-hyphen-pt#44]
https://github.com/leolca/tex-hyphen-pt/blob/dd17f359ec18c5fab0838453389bd8b4f40ca2b7/article/texrulespt.tex#L35

Fiquei tentando lembrar palavras que teriam o padrão W seguida de L ou R no português, há? Seria só para estrangeirismos, certo?

**Comment by leolca** [comment]
Realmente, não sei por que incluíram essas regras. Só encontrei estrangeirismos. Vou colocar esta observação nas notas de rodapé.
