### ISSUE TITLE
where

### ISSUE THREAD

**Issue by alinebenevides** [leolca/tex-hyphen-pt#45]
https://github.com/leolca/tex-hyphen-pt/blob/dd17f359ec18c5fab0838453389bd8b4f40ca2b7/article/methodology.tex#L8

Não seria 'quando necessário'? isto é, when no lugar de where..

**Comment by leolca** [comment]
"onde" necessário, referindo-se aos pontos/locais onde verifica-se a necessidade de realizar correção
