### ISSUE TITLE
Repensar exemplos

### ISSUE THREAD

**Issue by alinebenevides** [leolca/tex-hyphen-pt#51]
https://github.com/leolca/tex-hyphen-pt/blob/9a9491eabb5772facd659a408d9667bc94388593/article/updatingrules.tex#L127

Léo, 
fiquei pensando se vale colocar far-quhar e qu-bit, pois claramente não são palavras do português. Minha sugestão seria excluir, pois não são palavras da língua e não há adaptação fonotática da língua portuguesa para essas palavras, além de nem serem conhecidas

**Comment by alinebenevides** [comment]
Esses casos deveriam ser incluídos na seção estrangeirismo, não?

**Comment by leolca** [comment]
Acabei incluindo a regra dois motivos: 1) são estrangeirismos, porém com uma frequência de ocorrência baixa mas nem tão assim; 2) a regra faz sentido no português (possibilitar a hifenização antes de uma sequência -qu) e não atrapalha em nada (sem necessidade de criar regras de exceção).

**Comment by alinebenevides** [comment]
Tudo certo quanto a isso!
