### ISSUE TITLE
Rever erros

### ISSUE THREAD

**Issue by alinebenevides** [leolca/tex-hyphen-pt#56]
https://github.com/leolca/tex-hyphen-pt/blob/623e13e140beea0ce67fda5151c11424ea08e6ec/article/hyphenpatches.tex#L195

Léo, 
na tabela 5, há indicação dos seguintes exemplos como errados, mas, para mim, estariam certos:

a*cu-i*da*de --> a-cui-da-de
a*lu-i*men*to --> a-lui-men-to
es*pon*sa-is --> es-pon-sais
in*tu-i*ti*vo --> in-tui-ti-vo
núp*ci.as --> núp-cias

Faz sentido?

**Comment by leolca** [comment]
_acuidade_, _aluimento_ e _intuitivo_ estão com hifenização errada nos 5 dicionários... então acrescentei como ponto de correção manual.
As outras duas (_esponsais_ e _núpcias_) foram corrigidas no script que cria o dicionário 5.

a-cu-i-da-de(5)
a-lu-i-men-to(5)
es-pon-sais(5),es-pon-sa-is(1)
in-tu-i-ti-vo(5)
núp-ci-as(5),núp-cias(1)
