### ISSUE TITLE
incluir

### ISSUE THREAD

**Issue by alinebenevides** [leolca/tex-hyphen-pt#6]
pronounced - this is because Portuguese does not have a direct letter-sound correspondence, and vice versa.

**Comment by alinebenevides** [comment]
Traduzir car na última linha do parágrafo.

**Comment by leolca** [comment]
> pronounced - this is because Portuguese does not have a direct letter-sound correspondence, and vice versa.

importante citar o local no texto... você está criando as _issues_ sem referenciar o texto... note que nas primeiras criadas você fez corretamente
